version: '3.9'

services:
  web:
    build: .
    ports:
      - "8081:8081"
    environment:
      SERVICE_WEB_FOLDER: "web-folder/"
      SERVICE_DB_URL: "postgres://postgres:Mediomel€91@servidorvalero.ddns.net:5432/teacherinator"
      SERVICE_MONGO_DB_URL: "mongodb://127.0.0.1:27017"
      SERVICE_PWD_KEY: "gTNvn7X9LtlrgTtjCA5Sm5RHSSZ1YP_8kN2_U4Rj21fTvCHRrZu0YQPMnZNHvhQPaf8Hm40AAye8IuzZLyqijw"
      SERVICE_TOKEN_KEY: "UxYFNlatBv_YTaQgsn5-7udXjNf5qPJYkrllzZ8KTuDZU_mpETgRHVJWcVOBrMB4YhkxS7rNFeU9ATBfHspVJA"
      SERVICE_TOKEN_DURATION_SEC: "1800"
      ORIGIN_1: "http://127.0.0.1:3000"
      ORIGIN_2: "http://192.168.3.201:3000"
      ORIGIN_3: "http://servidorvalero.ddns.net:3000"