# Cargo config file

# Environments variables set for all `cargo ...` commands.
[env]

# Scope down tracing, to filter out external lib tracing
RUST_LOG = "teacherinator_web_server=debug,lib_core=debug,lib_auth=debug,lib_utils=debug"

# -- Service Environment Variables
# IMPORTANT:
#   For cargo commands only.
#   For deployed env, should be managed by container
#   (e.g., Kubernetes).

## -- Secrets
# Keys and passwords below are for localhost dev ONLY.
# e.g., "welcome" type of passwords.
# i.e., Encryption not needed.

SERVICE_DB_URL = "postgres://postgres:password@localhost:5432/teacherinator"

SERVICE_MONGO_DB_URL="mongodb://127.0.0.1:27017"
#SERVICE_MONGO_DB_URL="mongodb+srv://username:password@cluster.mongodb.net/?retryWrites=true&w=majority"

SERVICE_PWD_KEY="your_password_key"

SERVICE_TOKEN_KEY="your_token_key"
SERVICE_TOKEN_DURATION_SEC="1800"  # 30 min

## -- ConfigMap

SERVICE_WEB_FOLDER="web-folder/"